version: "2"
services:
  vue: 
    build: node-vue
    ports: 
      - "8080:8080"
    tty: true
    volumes:
    - ./:/app
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./:/usr/src/app:cached
      
